### ISSUE TITLE
Provide way to override the extenstion-to-content-model mapping

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/islandora_compound_batch#14]
This feature is listed in the README's  'todo'. I propose adding a drush option `--content_models` (for consistency with Islandora Batch) that would take as its value a semicolon-separated list of extension => content model pairs, with a double colon (`::`) as the delimiter within pairs, e.g., 

`--content_models=pdf::islandora:foo`
`--content_models=pdf::islandora:foo;jpg::islandora:barCModel`

If the `--content_models` parameter is present, its mappings would have precedence over the mappings defined in $this->extensionToContentModelMap.

If this sounds like a viable plan, I'd be happy to take a stab at it.

**Comment by mjordan** [comment]
A comma (`,`) is probably a better delimiter than a semicolon, if only for consistency with Islandora Batch's use of the `--content_models` option.

**Comment by egesu** [comment]
@mjordan I guess this won't affect ingesting metadata without any object, right? When I try to add just metadata, their content model becomes `compound content model`.

**Comment by mjordan** [comment]
@egesu, when you say "just metadata", do you mean at the child level, like this?

```
input_directory
├── parent_one
│   ├── first_child
│   │   ├── MODS.xml
│   ├── second_child
│   │   ├── MODS.xml
│   └── MODS.xml
└── parent_two
    ├── first_child
    │   ├── MODS.xml
    ├── second_child
    │   ├── MODS.xml
    └── MODS.xml
```

And if so, are the child objects getting a content model of compound? I can test later but I want to make sure I clearly understand you use case.

**Comment by egesu** [comment]
@mjordan Exactly! I will also test again to make sure I didn't do any mistake.

**Comment by mjordan** [comment]
@egesu when I batch load the following input data:

```
/tmp/compound_no_payload/
├── compound1
│   ├── 01
│   │   └── MODS.xml
│   ├── 02
│   │   └── MODS.xml
│   ├── 03
│   │   └── MODS.xml
│   ├── MODS.xml
│   └── structure.xml
└── compound2
    ├── 01
    │   ├── MODS.xml
    │   └── OBJ.tif
    ├── 02
    │   ├── MODS.xml
    │   └── OBJ.pdf
    ├── 03
    │   ├── MODS.xml
    │   └── OBJ.jpg
    ├── 04
    │   ├── MODS.xml
    │   └── OBJ.tif
    ├── MODS.xml
    └── structure.xml
```

for compound1, only the parent compound object is created, none of the chlldred (i.e., with MODS.xml only) are. This behaviour is consistent with the code at https://github.com/MarcusBarnes/islandora_compound_batch/blob/master/includes/preprocessor.inc#L44.

If I understand your use case, you are wanting to create child objects using only MODS (or MARC) XML files and then add the payload (PDF, image, etc.) file later. If that's the case (and I think it is a valid use case), we probably should open a new issue to address it. @MarcusBarnes do you have any thoughts on this?

I'm going to open a PR for the current issue, since I don't think it affects the use case you are describing. If I am misunderstanding something, please let me know. I'll wait for @MarcusBarnes to weigh in but we can follow up in the relevant issue.

**Comment by mjordan** [comment]
PR: https://github.com/MarcusBarnes/islandora_compound_batch/pull/15

**Comment by MarcusBarnes** [comment]
It's an interesting valid use case which should probably be supported.

**Comment by mjordan** [comment]
Perhaps one implementation would be to  provide yet another command-line option that let you specify which content model objects with no payload should get.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/islandora_compound_batch/pull/15.  Merged into master with commit https://github.com/MarcusBarnes/islandora_compound_batch/commit/0f6d81fb35cd1ddd38c16d5ed31be75753967e7f.

**Comment by mjordan** [comment]
@MarcusBarnes thanks! I can open an issue for the metadata-only use case if you want.

**Comment by MarcusBarnes** [comment]
@mjordan Yes, please.  Thank you.
