### ISSUE TITLE
Update Drush option names to work with latest drush versions

### ISSUE THREAD

**Issue by jpeak5** [MarcusBarnes/islandora_compound_batch#19]
I found that I was unable to run `drush icbp` using later versions of drush; I'm on a pretty recent version, 9.0-dev.

Anyway, it turned out that using an option name other than `target` to indicate the source directory made my errors go away. Unfortunately, I made this fix long ago on our fork (which is somehow no longer linked), so I don't have error output or anything to help explain why I've made this change.

Maybe I'll just leave this here in case it can be useful: https://github.com/lsulibraries/islandora_compound_batch/commit/422e2e08fb99981c1e3aa98131fed51de0d3415b

**Comment by MarcusBarnes** [comment]
Thanks @jpeak5 - I'll look at this when I review issue https://github.com/MarcusBarnes/islandora_compound_batch/issues/18.

**Comment by mjordan** [comment]
Sounds like we should be following the approach of the other batch modules, which use `--scan_target` when Drush is version 7 or higher (see https://github.com/Islandora/islandora_batch).

**Comment by mjordan** [comment]
@jpeak5 and @MarcusBarnes, what do you think of rolling the drush version check and using `--target`/`--scan_target` in with work on #20? I'm happy to do the coding.

**Comment by shorock** [comment]
Yep, like @jpeak5 we have a local fork for this one. https://github.com/MarcusBarnes/islandora_compound_batch/compare/master...shorock:drush7-scan_target  +1 on fixing.

**Comment by jpeak5** [comment]
sorry folks, I was traveling, and this slipped my attention; I agree with your proposal @mjordan to use options based on drush version...

**Comment by MarcusBarnes** [comment]
Address in pull-request https://github.com/MarcusBarnes/islandora_compound_batch/pull/21 (merged with commit https://github.com/MarcusBarnes/islandora_compound_batch/commit/0a0a357b49b14fa3419d14cdcdb4b974854a90a5).
