### ISSUE TITLE
Consider natural language sort order in create_structure_files

### ISSUE THREAD

**Issue by whikloj** [MarcusBarnes/islandora_compound_batch#24]
I'm building some compounds and trying this out again. I noticed that because I use a numbering scheme to generate my sub-directories they fall out of order if there are more than 9 items. 
ie.
```
<islandora_compound_object title="pa_aar">
  <child content="pa_aar/1"/>
  <child content="pa_aar/10"/>
  <child content="pa_aar/2"/>
  <child content="pa_aar/3"/>
  <child content="pa_aar/4"/>
  <child content="pa_aar/5"/>
  <child content="pa_aar/6"/>
  <child content="pa_aar/7"/>
  <child content="pa_aar/8"/>
  <child content="pa_aar/9"/>
</islandora_compound_object>
```
Adding a natural language sort (or perhaps a configurable sort option) would help.

I just added this line
```
sort($stuffindirectory, SORT_NATURAL);
```
below [here](https://github.com/MarcusBarnes/islandora_compound_batch/blob/master/extras/scripts/create_structure_files.php#L129) which results in my desired ordering.
```
<islandora_compound_object title="pa_aar">
  <child content="pa_aar/1"/>
  <child content="pa_aar/2"/>
  <child content="pa_aar/3"/>
  <child content="pa_aar/4"/>
  <child content="pa_aar/5"/>
  <child content="pa_aar/6"/>
  <child content="pa_aar/7"/>
  <child content="pa_aar/8"/>
  <child content="pa_aar/9"/>
  <child content="pa_aar/10"/>
</islandora_compound_object>
```

**Comment by MarcusBarnes** [comment]
@whikloj If I was to make the suggested change, would you be able to test the resulting pull-request?

**Comment by whikloj** [comment]
@MarcusBarnes I could certainly test it with my data, but it would be beneficial to have some other examples and how they currently operate. I don't want this to cause people's existing workflow to change if that can be avoided.

Even if we could brainstorm some example structures, I would be willing to try and write some simple PHPUnit tests to ensure stability.

**Comment by MarcusBarnes** [comment]
OK.  Sounds good.  @mjordan, do you think whikloj suggested change would cause any potential issues with how you use compound batch?

**Comment by mjordan** [comment]
No issues for me, thanks for catching this @whikloj.

**Comment by cdeaneGit** [comment]
Hi Jared,

BRAVO!!!!

cheers!
cricket!

**Comment by cdeaneGit** [comment]
Hi Guys,

I have data I just ingested using my compound_prep.py script (https://github.com/cdeaneGit/compound_prep) to prepare the data for islandora_compound_batch, which worked perfectly.

I had my seed set to 1000 to make all the directories be numbered above 1000 and avoid the ordering problem, but I will reset to 0 and test the some of the same data with the latest version of islanodra_compound_batch on our test repository.

cheers!
cricket!

**Comment by MarcusBarnes** [comment]
I'm glad to know @whikloj and @cdeaneGit that you're exploring or using this module.  I hope to get some time to work on this tomorrow or Friday and then I'll submit a pull-request for testing and review.

**Comment by whikloj** [comment]
@cdeaneGit Ha I wish I had known about your script. I actually just wrote a python script for exactly the same purpose (https://github.com/whikloj/build_compounds). I'll have to peruse your repos.

**Comment by MarcusBarnes** [comment]
A pull-request is ready to be tested:  https://github.com/MarcusBarnes/islandora_compound_batch/pull/25  Please add a comment to the pull-request the results of your testing.  If we don't get any issues, @mjordan or myself will merge.  Thank you in advance.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/islandora_compound_batch/pull/25 (merged with commit https://github.com/MarcusBarnes/islandora_compound_batch/commit/333874986577b773a07acde385effde93206db49).  Thank you @whikloj @mjordan @cdeaneGit  for your feedback regarding this issue.

**Comment by cdeaneGit** [comment]
I tested the new version vs. the old version on the same data that has 29 pages.

The sorting with the old was the “alphabetical-numeric” sort.
The sorting with the new was straight numerical.  Perfect.

Thanks for improvement!

cheers!
cricket!
