### ISSUE TITLE
Allow assignment of content model for parent objects

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/islandora_compound_batch#26]
If you uncheck the option "Only allow compound objects to have child objects associated with them" at admin/islandora/solution_pack_config/compound_object (Administration > Islandora > Solution Pack Configuration > Compound Object Solution Pack), any object, regardless of its content model, can have children. Currently, the content model of the parent objects created by this module is hard coded at https://github.com/MarcusBarnes/islandora_compound_batch/blob/master/includes/object.inc#L175. It would be useful to all the user to pass in a `--parent_content_model` parameter to override this.

**Comment by mjordan** [comment]
I'll work on a PR for this.

**Comment by mjordan** [comment]
Thinking about this a bit more, we probably want to provide a couple options:

* Since each parent object can have a binary file (image, PDF, video, etc.), we probably want to all for autodetection of a parent's content model, probably using the [extension to content model map](https://github.com/MarcusBarnes/islandora_compound_batch/blob/master/includes/utilities.inc#L17), consistent with [this cryptic comment](https://github.com/MarcusBarnes/islandora_compound_batch/blob/master/includes/object.inc#L173).

For example, if we had input like this:

```
input_directory
├── parent_one
│   ├── first_child
│   │   ├── MODS.xml
│   │   └── OBJ.jp2
│   ├── second_child
│   │   ├── MODS.xml
│   │   └── OBJ.jp2
│   └── MODS.xml
│   └── foo.tiff  // <- parent_one's binary
└── parent_two
    ├── first_child
    │   ├── MODS.xml
    │   └── OBJ.jp2
    ├── second_child
    │   ├── MODS.xml
    │   └── OBJ.jp2
    └── bar.pdf  // <- parent_two's binary
    └── MODS.xml
```
The presence of `foo.tiff` would assign the `islandora:sp_large_image_cmodel` content model to parent_one, and the presence of `bar.pdf` would assign the `islandora:sp_pdf` content model to  parent_two.

* Since the OBJ is [not required](https://jira.duraspace.org/browse/ISLANDORA-1362), we probably want to provide a Drush parameter like `--parent_content_model` to allow the user to specify a content model for all parents in the batch, e.g., `--parent_content_model=islandora:sp_pdf`
* The default content model for parents would be as it is now, `islandora:compoundCModel`.

Questions about the first example, where the parents have binary files that determine their content models:

1. should we require a drush parameter (maybe something like `--parent_content_model=all`?) or let the mere presence of a binary file at the parent level determine what content model to assign?
1. in the first example, if there is no binary, do we default to `islandora:compoundCModel`?

**Comment by mjordan** [comment]
@MarcusBarnes any thoughts on the previous comment?

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/islandora_compound_batch/pull/35 (merged with commit https://github.com/MarcusBarnes/islandora_compound_batch/commit/153903765a61eb0f938e8c10468b3d3d213a1e81).
