### ISSUE TITLE
Use value of Child relationship predicate setting rather than the default.

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/islandora_compound_batch#28]
We have been assuming the the Child relationship predicate is the default 'isConstituentOf' in the addRelationshipsForChild method https://github.com/MarcusBarnes/islandora_compound_batch/blob/0f6d81fb35cd1ddd38c16d5ed31be75753967e7f/includes/object.inc#L181. However,  this value is configurable in the 'Child relationship predicate' setting on the compound object solution pack admin form admin/islandora/solution_pack_config/compound_object form.   Rather than assuming that it will be the default 'isConstituentOf' (with the same caveats on that changing that setting in the compound object solution pack admin form after the fact), use the value of the 'Child relationship predicate' setting.

Thanks to @bseeger for spotting this (see https://github.com/MarcusBarnes/islandora_compound_batch/issues/27#issuecomment-403530044).

**Comment by mjordan** [comment]
@bseeger totally, thanks very much for pointing out this important omission.

**Comment by bseeger** [comment]
Thanks @mjordan and @MarcusBarnes!
