### ISSUE TITLE
Utilities class's name is "Utilies"

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/islandora_compound_batch#34]
This looks like a typo. Should be change it to "Utilities"?

**Comment by MarcusBarnes** [comment]
@mjordan Yes, appears to be a typo - replacing all references and confirming that everything still works should resolve this.  Thanks!

**Comment by mjordan** [comment]
I'm working on #26 - mind if I change it as part of that?

**Comment by MarcusBarnes** [comment]
Addressed as part of pull-request #35 (merged with commit 1539037).

**Comment by mjordan** [comment]
Closed as part of #35.
